
builds:
  - id: xtask 
    binary: xtask
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./main.go
    hooks:
      pre: go mod tidy
      post: go mod tidy

checksum:
  # You can change the name of the checksums file.
  #
  # Default: '{{ .ProjectName }}_{{ .Version }}_checksums.txt', or,
  #   when split is set: '{{ .ArtifactName }}.{{ .Algorithm }}'.
  # Templates: allowed.
  name_template: "{{ .ProjectName }}-checksums.txt"

archives:
  - id: xtask
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
    format_overrides:
      - goos: windows
        formats: [zip, tar.gz]

    files:
      - LICENSE.md
      - README.md

nfpms:
  - id: xtask
    description:  |
      xtask is a command-line tool for defining and executing common tasks."
    homepage: "https://github.com/hyprxlabs/xtask"
    file_name_template: "{{ .PackageName }}-{{ .Os }}-{{ .Arch}}-{{ .Version }}"
    maintainer: "Hyprxdev <180069990+hyprxdev@users.noreply.github.com>"
    license: "MIT"
    formats:
      - deb
      - rpm
      - archlinux
      - apk

chocolateys:
  - name: xtask
    description: |
      A cross-platform command-line tool for defining and executing
      common tasks.

      The `xtask` command allows you to define tasks in a YAML file and execute
      them from the command line.

      The environment variables support environment variable
      expansion and command substitution.
    package_source_url: "https://github.com/hyprxlabs/xtask"
    title: "xtask"
    project_url: "https://github.com/hyprxlabs/xtask"
    copyright: "Copyright © 2025 hyprxdev hyprxlabs"
    require_license_acceptance: false
    icon_url: "https://raw.githubusercontent.com/hyprxlabs/dotnet/refs/heads/main/eng/assets/hyprx_logo_256.png"
    authors: "Hyprxdev <180069990+hyprxdev@users.noreply.github.com>"
    tags: "env xtask run command dotenv"
    summary: " A cross-platform command-line tool for defining and executing
      common tasks."
    release_notes: "https://github.com/foo/bar/releases/tag/v{{ .Version }}"
    skip_publish: true

    